#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSource")]
	public partial class ConnectionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ConnectionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarUsuario")]
		public int sp_ActualizarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nombre, apellidos, email, direccion, telefono, descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CrearUsuario")]
		public int sp_CrearUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, apellidos, email, password, direccion, telefono, descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarUsuario")]
		public int sp_EliminarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_IngresarCalificacion")]
		public int sp_IngresarCalificacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> calificacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, calificacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_obtener_usuario_por_id")]
		public ISingleResult<sp_obtener_usuario_por_idResult> sp_obtener_usuario_por_id([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<sp_obtener_usuario_por_idResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_obtener_usuario_por_idResult
	{
		
		private long _tb_usuario_id;
		
		private string _tb_usuario_nombre;
		
		private string _tb_usuario_apellidos;
		
		private string _tb_usuario_email;
		
		private string _tb_usuario_password;
		
		private string _tb_usuario_direccion;
		
		private string _tb_usuario_telefono;
		
		private System.Nullable<int> _tb_usuario_calificacion;
		
		private string _tb_usuario_descripcion;
		
		private System.Nullable<byte> _tb_usuario_estado;
		
		public sp_obtener_usuario_por_idResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_usuario_id", DbType="BigInt NOT NULL")]
		public long tb_usuario_id
		{
			get
			{
				return this._tb_usuario_id;
			}
			set
			{
				if ((this._tb_usuario_id != value))
				{
					this._tb_usuario_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_usuario_nombre", DbType="VarChar(255)")]
		public string tb_usuario_nombre
		{
			get
			{
				return this._tb_usuario_nombre;
			}
			set
			{
				if ((this._tb_usuario_nombre != value))
				{
					this._tb_usuario_nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_usuario_apellidos", DbType="VarChar(255)")]
		public string tb_usuario_apellidos
		{
			get
			{
				return this._tb_usuario_apellidos;
			}
			set
			{
				if ((this._tb_usuario_apellidos != value))
				{
					this._tb_usuario_apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_usuario_email", DbType="VarChar(255)")]
		public string tb_usuario_email
		{
			get
			{
				return this._tb_usuario_email;
			}
			set
			{
				if ((this._tb_usuario_email != value))
				{
					this._tb_usuario_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_usuario_password", DbType="VarChar(255)")]
		public string tb_usuario_password
		{
			get
			{
				return this._tb_usuario_password;
			}
			set
			{
				if ((this._tb_usuario_password != value))
				{
					this._tb_usuario_password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_usuario_direccion", DbType="VarChar(255)")]
		public string tb_usuario_direccion
		{
			get
			{
				return this._tb_usuario_direccion;
			}
			set
			{
				if ((this._tb_usuario_direccion != value))
				{
					this._tb_usuario_direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_usuario_telefono", DbType="VarChar(255)")]
		public string tb_usuario_telefono
		{
			get
			{
				return this._tb_usuario_telefono;
			}
			set
			{
				if ((this._tb_usuario_telefono != value))
				{
					this._tb_usuario_telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_usuario_calificacion", DbType="Int")]
		public System.Nullable<int> tb_usuario_calificacion
		{
			get
			{
				return this._tb_usuario_calificacion;
			}
			set
			{
				if ((this._tb_usuario_calificacion != value))
				{
					this._tb_usuario_calificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_usuario_descripcion", DbType="VarChar(255)")]
		public string tb_usuario_descripcion
		{
			get
			{
				return this._tb_usuario_descripcion;
			}
			set
			{
				if ((this._tb_usuario_descripcion != value))
				{
					this._tb_usuario_descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_usuario_estado", DbType="TinyInt")]
		public System.Nullable<byte> tb_usuario_estado
		{
			get
			{
				return this._tb_usuario_estado;
			}
			set
			{
				if ((this._tb_usuario_estado != value))
				{
					this._tb_usuario_estado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
