//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQL5113.site4now.net;Persist Security Info=True;User ID=db_aa7784_bde" +
            "mprende_admin;TrustServerCertificate=True")]
        public string DataSourceConnectionString {
            get {
                return ((string)(this["DataSourceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQL5113.site4now.net;Persist Security Info=True;User ID=db_aa7784_bde" +
            "mprende_admin;Password=una123456;TrustServerCertificate=True")]
        public string DataSourceConnectionString1 {
            get {
                return ((string)(this["DataSourceConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-GS5ITPH\\FERNANDO;Initial Catalog=SarapiquiEmprende;Integrated" +
            " Security=True;TrustServerCertificate=True")]
        public string SarapiquiEmprendeConnectionString {
            get {
                return ((string)(this["SarapiquiEmprendeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQL5113.site4now.net;Persist Security Info=True;User ID=db_aa7784_bde" +
            "mprende_admin;Password=una123456;Encrypt=True;TrustServerCertificate=True")]
        public string db_aa7784_bdemprendeConnectionString {
            get {
                return ((string)(this["db_aa7784_bdemprendeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQL5113.site4now.net;Persist Security Info=True;User ID=db_aa7784_bde" +
            "mprende_admin;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString2 {
            get {
                return ((string)(this["DataSourceConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQL5113.site4now.net;Initial Catalog=db_aa7784_bdemprende;Persist Sec" +
            "urity Info=True;User ID=db_aa7784_bdemprende_admin;Encrypt=True;TrustServerCerti" +
            "ficate=True")]
        public string db_aa7784_bdemprendeConnectionString1 {
            get {
                return ((string)(this["db_aa7784_bdemprendeConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQL5113.site4now.net;Initial Catalog=db_aa7784_bdemprende;Persist Sec" +
            "urity Info=True;User ID=db_aa7784_bdemprende_admin;Password=una123456;Encrypt=Tr" +
            "ue;TrustServerCertificate=True")]
        public string db_aa7784_bdemprendeConnectionString2 {
            get {
                return ((string)(this["db_aa7784_bdemprendeConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Initial Catalog=db_aa995b_emprende;Persist Secur" +
            "ity Info=True;User ID=db_aa995b_emprende_admin;Password=una123456;TrustServerCer" +
            "tificate=True")]
        public string db_aa995b_emprendeConnectionString {
            get {
                return ((string)(this["db_aa995b_emprendeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString3 {
            get {
                return ((string)(this["DataSourceConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString4 {
            get {
                return ((string)(this["DataSourceConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString5 {
            get {
                return ((string)(this["DataSourceConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString6 {
            get {
                return ((string)(this["DataSourceConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Password=una123456;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString7 {
            get {
                return ((string)(this["DataSourceConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString8 {
            get {
                return ((string)(this["DataSourceConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString9 {
            get {
                return ((string)(this["DataSourceConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString10 {
            get {
                return ((string)(this["DataSourceConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString11 {
            get {
                return ((string)(this["DataSourceConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString12 {
            get {
                return ((string)(this["DataSourceConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString13 {
            get {
                return ((string)(this["DataSourceConnectionString13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString14 {
            get {
                return ((string)(this["DataSourceConnectionString14"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString15 {
            get {
                return ((string)(this["DataSourceConnectionString15"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString16 {
            get {
                return ((string)(this["DataSourceConnectionString16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString17 {
            get {
                return ((string)(this["DataSourceConnectionString17"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Encrypt=True;TrustServerCertificate=True")]
        public string DataSourceConnectionString18 {
            get {
                return ((string)(this["DataSourceConnectionString18"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Initial Catalog=db_aa995b_emprende;Persist Secur" +
            "ity Info=True;User ID=db_aa995b_emprende_admin;Password=una123456;Encrypt=True;T" +
            "rustServerCertificate=True")]
        public string db_aa995b_emprendeConnectionString1 {
            get {
                return ((string)(this["db_aa995b_emprendeConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql8010.site4now.net;Persist Security Info=True;User ID=db_aa995b_emp" +
            "rende_admin;Encrypt=True")]
        public string DataSourceConnectionString19 {
            get {
                return ((string)(this["DataSourceConnectionString19"]));
            }
        }
    }
}
